# Generated by Django 6.0.1 on 2026-04-13 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('completed', 'Completed')], default='open', max_length=10)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='pool.season')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('season', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('kickoff', models.DateTimeField()),
                ('winner', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pool.week')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='pool.week')),
            ],
            options={
                'unique_together': {('user', 'week')},
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('predicted_winner', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('locked', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='pool.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='pool.week')),
            ],
            options={
                'unique_together': {('user', 'week', 'game')},
            },
        ),
    ]
