# Generated by Django 6.0.1 on 2026-05-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_game_away_moneyline_game_espn_id_game_home_moneyline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
