# Generated by Django 6.0.1 on 2026-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_favorite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='', help_text='A short status phrase shown next to your name.', max_length=60),
        ),
    ]
